### ISSUE TITLE
Error: UnknownError seemingly connected to hostname

### ISSUE THREAD

**Issue by kaihoffman** [civo/cli#104]
Raised by a customer, this is a case of the CLI returning an opaque "UnknownError" which I think may be related to there being a limit to what is an acceptable hostname length?

```
civo instance create -s foob-1.barfooo.foob.barrfoobazzz.co.uk -i g3.medium -t d927ad2f-5073-4ed6-b2eb-b8e61aef29a8
Error: UnknownError
```
(I have obfuscated the hostname from the original, the one above is in the same format and the same length in all sections)

however, with the only thing changing being the hostname:

```
$ civo instance create -s abc.co.uk -i g3.medium -t d927ad2f-5073-4ed6-b2eb-b8e61aef29a8
The instance abc.co.uk has been created
```

It would be important to get a clearer error message, and to have hostnames work as long as they correspond to the fully qualified domain name spec.

Assigned to you Harsh, on advice from Andy. Please let me know if you need any more context.

**Comment by kaihoffman** [comment]
This might actually have to do with the fact that the Civo Kubernetes platform needs to handle longer metadata labels to reduce them to less than 64 characters. I know @banksyian is looking at the issue on the internal side so worth checking if this fixes itself after that commit @RealHarshThakur

**Comment by RealHarshThakur** [comment]
@kaihoffman not exactly sure if this will fix it but I remember running into a this issue(or similar one) with a different project and the fix was to not use `Update` or `Apply` . We had to use `Create` or `Replace`. So basically, kubectl create or replace operation on the resource would succeed. The reason being that there's a size limitation on the object being stored in etcd and using kubectl apply keeps the previous configuration of the object which increases the size.

**Comment by banksyian** [comment]
I am familiar with the type of error you are referring to @RealHarshThakur, the issue @kaihoffman is referring to is different, it is a limitation with Kubevirt VM name length.
