### ISSUE TITLE
cluster scaling - message appears, but doesn't scale when specifying pool-id in quotes

### ISSUE THREAD

**Issue by xw-patrick** [civo/cli#108]
civo k8s pool scale demo-cluster $(civo k8s show demo-cluster --region=${REGION} -o json | jq ".pools[0].id") -n 4 --region=${REGION}
==> shows successful response:
The pool ("8c010bc4-61bd-49b2-9ba5-0c7ff5c57617") was scaled to (4) in the cluster ( demo-cluster)
==> but nothing happens - no scaling initiated.

==> when specifying pool-id without quotes, the scaling works:
civo k8s pool scale demo-cluster $(civo k8s show demo-cluster --region=${REGION} -o json | jq -r ".pools[0].id") -n 4 --region=${REGION}
(the difference is the "-r" after jq)

either the first attempt should scale - or it should respond with an appropriate error message...

**Comment by zulh-civo** [comment]
I don't think this is a CLI bug. It's more to jq's behaviour when `--raw-output|-r` flag is not provided. If you provide `-r` flag, you will get a result without quotes. For example:

```
$ civo k8s show demo-cluster --region=${REGION} -o json | jq --raw-output ".pools[0].id"
01503075-9f6a-4cd7-83cd-6409a9a95884

$ civo k8s show demo-cluster --region=${REGION} -o json | jq ".pools[0].id"
"01503075-9f6a-4cd7-83cd-6409a9a95884"
```

Because the pool ID is the second argument to 'scale' command, it's common to provide it (as argument) in form of string, without quotes. It's rare if you need to use `civo k8s pool scale "demo-cluster" "the-pool-id"` here.

Unless it's a flag like below where both cases will work.

```
$ civo k8s ls --region=LON1
+--------------------------------------+--------------+--------+-------+-------+--------+
| ID                                   | Name         | Region | Nodes | Pools | Status |
+--------------------------------------+--------------+--------+-------+-------+--------+
| 2399b57c-b38b-4fe4-8cd8-f595f825f741 | demo-cluster | LON1   |     3 |     1 | ACTIVE |
+--------------------------------------+--------------+--------+-------+-------+--------+

$ civo k8s ls --region="LON1"
+--------------------------------------+--------------+--------+-------+-------+--------+
| ID                                   | Name         | Region | Nodes | Pools | Status |
+--------------------------------------+--------------+--------+-------+-------+--------+
| 2399b57c-b38b-4fe4-8cd8-f595f825f741 | demo-cluster | LON1   |     3 |     1 | ACTIVE |
+--------------------------------------+--------------+--------+-------+-------+--------+
```

I'm going to close this for now. If you think this shouldn't be the way, feel free to reopen and provide reasons. Thanks.
