### ISSUE TITLE
How do we rebuild or move an IP?

### ISSUE THREAD

**Issue by iambenmitchell** [civo/cli#154]
Recently you decided to stop us from moving IPs between instances, yet we cannot rebuild an instance. How do you propose we reset an instance without losing the IP address

**Comment by zulh-civo** [comment]
@iambenmitchell - the "move IP" was a feature in our previous stack. It's not available yet in our new [CivoStack](https://www.civo.com/blog/new-year-new-york-new-civostack). There's no plan/date yet when we are going to put back the "move IP" feature, I'm sorry. Perhaps @andyjeffries has something to say.

**Comment by andyjeffries** [comment]
I just want to say that this wasn't a conscious decision to _remove_ the functionality (we didn't decide to stop), rather we built CivoStack primarily to support customer managed Kubernetes as that is our core business, the Compute service is really seen internally as an add-on to our Kubernetes service rather than the core service itself. 

So as the work in CivoStack didn't naturally support it with the way it works, the functionality wasn't written in there (the percentage of customers that use Compute services is really tiny, and those that ever need to move an IP is smaller still). If this is a key feature for you, we have roadmap planning today so I'll discuss with our tech leadership the effort to support it and see if we can schedule it in during this next phase.

**Comment by iambenmitchell** [comment]
> if this is a key feature for you, we have roadmap planning today so I'll discuss with our tech leadership the effort to support it and see if we can schedule it in during this next phase.

I wouldn't need to be able to move an IP if I could rebuild an instance instead, that is what I was trying to originally do. Thanks for the reply though :) I have been using CIVO since it was in Beta back in 2017 or 2018 I think, still have my Civo stickers. Back then, the instances were the core focus of the business I thought.

Anyways, thanks again. In the meantime is there a method I could use to rebuild an instance or is there an old version of the CLI I can use to move the IP?

**Comment by zulh-civo** [comment]
@iambenmitchell - we do not have "instance rebuild" feature in our CivoStack yet. We are considering to have it — but there's no solid timeline for it yet because we think this is low priority for now.

Should you need to rebuild your instance and keep the IP, please get in touch with us via [Slack](https://app.slack.com/client/TKW8H5MBK/CMVCKMCN5) / [Civo support](https://www.civo.com/contact). Our SRE team will help you with that (it will be a manual process by us). I hope this clarifies.
