### ISSUE TITLE
When deleting an instance it won't allow deletion of a specific name of instance if one of a similar names exisits

### ISSUE THREAD

**Issue by markboost** [civo/cli#31]
The name seems to be a fuzzy match rather than a specific exact match. Should this be an exact name only instead.

See attachment for example.

![image](https://user-images.githubusercontent.com/15697112/97476005-d7ddb080-1945-11eb-8806-1d22ed69093d.png)

**Comment by alejandrojnm** [comment]
@markboost I will check this

**Comment by andyjeffries** [comment]
Maybe we do both - it checks if the name matches exactly, if it does then use that. If there are multiple matches (but no exact match) error out, but add something like `, in order to ensure it's the right one please use the ID instead of part of the name`. And finally if no exact match but a fuzzy match finds one, then use that.

**Comment by andyjeffries** [comment]
Much more user friendly than a) always requiring an exact match or b) always doing a fuzzy/partial match but not allowing deletion if more than one match.

**Comment by alejandrojnm** [comment]
May be we can ask for the id, when we found a multiple mach like:
```
civo k3s rm Garcia
Warning: we found more than one result, in order to ensure it's the right one please type the ID
```
if the id is provide, we delete the resource

**Comment by andyjeffries** [comment]
I'm happy with either a corrected message OR moving to a "strict match" (not contains, but `==`) then a partial match.
